version: "3.8"

services:
  data-collector:
    build: ./data-collector
    restart: unless-stopped
    container_name: data-collector
    volumes:
      - data-volume:/app/data
    ports:
      - "8002:8000"
    environment:
      - HA_URL=${HA_URL}
      - HA_TOKEN=${HA_TOKEN}
      - LAT=${LAT}
      - LON=${LON}
    networks:
      - meteo_network
    develop:
      watch:
        - action: sync+restart
          path: ./data-collector
          target: /app

  ml-engine:
    build: ./ml-engine
    container_name: ml-engine
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - data-volume:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - meteo_network
    develop:
      watch:
        - action: sync+restart
          path: ./ml-engine
          target: /app

  web-ui:
    build: ./web-ui
    restart: unless-stopped
    container_name: web-ui
    ports:
      - "${WEB_PORT:-8000}:8000"
    volumes:
      - data-volume:/app/data
    environment:
      - HA_URL=${HA_URL}
      - HA_TOKEN=${HA_TOKEN}
      - ML_ENGINE_URL=http://ml-engine:8000
    networks:
      - meteo_network
    develop:
      watch:
        # Synchronise le code Python à chaud
        - action: sync+restart
          path: ./web-ui
          target: /app
          ignore:
            - templates/
        # Synchronise les templates HTML instantanément (très pratique pour le front)
        - action: sync
          path: ./web-ui/templates
          target: /app/templates

  cron:
    image: alpine
    restart: unless-stopped
    container_name: scheduler
    command: >
      /bin/sh -c "echo '8,38 * * * * wget -qO- http://data-collector:8000/api/collect' > /etc/crontabs/root &&
                  echo '0 3 * * * wget -qO- http://ml-engine:8000/api/train' >> /etc/crontabs/root &&
                  crond -f -l 8"
    networks:
      - meteo_network

networks:
  meteo_network:
    driver: bridge

volumes:
  data-volume: